# -*- coding: utf-8 -*-
"""makeGraph_QuickSortTest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1niRmkAnQiwbzD7RUZ5iw33KwzpjgELxr
"""

from google.colab import drive
drive.mount('/content/gdrive')

times = []
implement = []
original = []

with open('/content/gdrive/My Drive/resData/result.txt') as file_object :
  while True :
    line = file_object.readline()[:-1]
    if not line : break
    res = line.split(',')
    times.append(res[0])
    implement.append(res[1])
    original.append(res[2])

import numpy as np

from matplotlib import pyplot as plt
import numpy as np

plt.xticks(np.arange(int(min(times)), int(max(times))),fontsize=10)
plt.yticks(np.arange(float(min(implement)), float(max(implement))),fontsize=10)
plt.plot(times, implement)
plt.plot(times, original)
plt.xlabel("Max Length of Array")
plt.ylabel("Running Time")
plt.show()